application: stackguru
version: 2
runtime: python
api_version: 1

handlers:
- url: /tasks/scan_new_questions/
  script: tasks/scan_new_questions.py
  login: admin
- url: /tasks/scan_new_questions/(.*)
  script: tasks/scan_new_questions.py  
- url: /tasks/scan_new_comments/
  script: tasks/scan_new_comments.py
  login: admin
- url: /ranks/
  script: ranks.py
- url: /answers/(.*)
  script: tasks/scan_new_comments.py  
- url: /comments/(.*)
  script: tasks/scan_new_comments.py

- url: /chrome/(.*)
  script: chrome.py

- url: /c/(.*)
  script: short_urls.py

- url: /follow/(.*)
  script: follow_question.py
- url: /unfollow/(.*)
  script: follow_question.py

- url: /tag/(.*)
  script: follow_tag.py
- url: /untag/(.*)
  script: follow_tag.py

- url: /tag/(.*)
  script: follow_tag.py
- url: /untag/(.*)
  script: follow_tag.py

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /test.*
  script: gaeunit.py
  login: admin
  
- url: /_wave/robot/profile
  static_files: static/wave/profile.txt  
  upload: static/wave/profile.txt  
- url: /.*
  script: main.py
  
inbound_services:
- xmpp_message

derived_file_type:
- python_precompiled