application: command-line-argument
version: 1
runtime: python27
threadsafe: yes
api_version: 1

handlers:  
- url: /tasks/scan_new_questions.*
  script: tasks.scan_new_questions.app 
  
- url: /tasks/scan_new_comments.*
  script: tasks.scan_new_comments.app
  login: admin

- url: /tasks/delete_old_questions_follow
  script: tasks.delete_old_questions_follow.app
  login: admin
  
- url: /answers/.*
  script: tasks.scan_new_comments.app
  
- url: /comments/.*
  script: tasks.scan_new_comments.app

- url: /chrome/.*
  script: chrome.app

- url: /c/.*
  script: short_urls.app

- url: /(follow|unfollow)/.*
  script: follow_question.app

- url: /(tag|untag)/.*
  script: follow_tag.app

- url: /_ah/xmpp/presence/.*
  script: xmpp_handler.app
  login: admin
   
- url: /.*
  script: main.app
  
inbound_services:
- xmpp_message
- xmpp_presence
          
builtins:
- remote_api: on
- appstats: on