application: stackguru
version: 1
runtime: python
api_version: 1

handlers:
- url: /tasks/scan_new_questions/
  script: tasks/scan_new_questions.py
  login: admin
- url: /tasks/scan_new_questions/(.*)
  script: tasks/scan_new_questions.py  
- url: /tasks/scan_new_comments/
  script: tasks/scan_new_comments.py
  login: admin
- url: /ranks/
  script: ranks.py
- url: /answers/(.*)
  script: tasks/scan_new_comments.py  
- url: /comments/(.*)
  script: tasks/scan_new_comments.py
  
- url: /_wave/robot/profile
  static_files: static/wave/profile.txt  
  upload: static/wave/profile.txt  
- url: /.*
  script: main.py
  
inbound_services:
- xmpp_message

derived_file_type:
- python_precompiled